### ISSUE TITLE
在苹果m1编译失败

### ISSUE THREAD

**Issue by wolftail** [bearlord/pdo_taos#2]
环境 m1  php7.2.16 tdengine 2.4.0
报错如下：
/pdo_taos/taos_driver.c:41:16: error: implicit declaration of function 'php_addcslashes_str' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return php_addcslashes_str(str, strlen(str), "\\'", sizeof("\\'"));
/pdo_taos/taos_driver.c:41:16: note: did you mean 'php_addcslashes'?
/usr/local/include/php/ext/standard/php_string.h:129:21: note: 'php_addcslashes' declared here
PHPAPI zend_string *php_addcslashes(zend_string *str, int freeit, char *what, size_t what_len);
                    ^
/pdo_taos/taos_driver.c:41:16: warning: incompatible integer to pointer conversion returning 'int' from a function with result type 'zend_string *' (aka 'struct _zend_string *') [-Wint-conversion]
        return php_addcslashes_str(str, strlen(str), "\\'", sizeof("\\'"));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/pdo_taos/taos_driver.c:149:19: warning: assigning to 'struct pdo_stmt_methods *' from 'const struct pdo_stmt_methods *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    stmt->methods = &taos_stmt_methods;
                  ^ ~~~~~~~~~~~~~~~~~~
/pdo_taos/taos_driver.c:415:18: warning: assigning to 'struct pdo_dbh_methods *' from 'const struct pdo_dbh_methods *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    dbh->methods = &taos_methods;
                 ^ ~~~~~~~~~~~~~

/pdo_taos/taos_driver.c:428:18: warning: assigning to 'struct pdo_dbh_methods *' from 'const struct pdo_dbh_methods *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    dbh->methods = &taos_methods;
                 ^ ~~~~~~~~~~~~~
4 warnings and 1 error generated.

**Comment by bearlord** [comment]
只在CentOS7和openSUSE15上跑过，还没在Mac上跑过了。已找到问题了，找个时间找朋友的Mac验证下。

**Comment by bearlord** [comment]
3个警告，在Linux，PHP7.2也复现了，开发环境是PHP.4，没兼容好PHP7.2。现在已做好7.1- 8.0的兼容并上传代码，PHP8.1还没适配。主要是 PHP内核定义的PDO的 const struct和 struct的区别。

1个错误，是暂时没有用到的代码，之前Linux下没报错，忽略了。现在对应的代码已删除。

你的涛思数据的库文件是在Mac上编译的吗? 官网默认没有MAC版本。
我的手边没有M1的MAC，无法测试。请从dev-master clone代码，再测试下吧。期待反馈。

**Comment by wolftail** [comment]
拉了最新版本，还是爆一下错误：

pdo_taos.c:73:67: error: use of undeclared identifier 'TSDB_DATA_TYPE_JSON'
    REGISTER_PDO_CLASS_CONST_LONG("PARAM_TAOS_JSON",  (zend_long)(TSDB_DATA_TYPE_JSON + 6000));
                                                                  ^
1 error generated.

**Comment by bearlord** [comment]
TSDB_DATA_TYPE_JSON，是TDengine 定义的。你用的TDengine的版本是多少？

**Comment by bearlord** [comment]
![1](https://user-images.githubusercontent.com/2367139/174700301-4983635e-68d6-45b3-96ac-d50063e51481.png)
![2](https://user-images.githubusercontent.com/2367139/174700312-ac2e9f1f-7f3a-4667-a4a3-a089482ae78d.png)

TSDB_DATA_TYPE_JSON 是2021年12月3日新增的代码。你用的TDengine 有点老?

**Comment by wolftail** [comment]
2.7.0.0

**Comment by bearlord** [comment]
> 2.7.0.0

噫，你这内部版本啊。发布版才2.6.0.4. 你看看的 taos.h的源文件，有没有 如下代码：

> #define TSDB_DATA_TYPE_UBIGINT    14    // 8 bytes
> #define TSDB_DATA_TYPE_JSON       15    // json string

taos.h一般在 /usr/local/taos/include目录下，或者你的TDengine目录下找找。

**Comment by wolftail** [comment]
看了一下，的确是之前安装的版本，然后全部删除，再clone最新代码安装，也是2.7.0.0。发现缺h文件，拷贝到/usr/local/taos/include目录后，再编译，还是报错如下：
In file included from /Users/xxxx/Documents/src/pdo_taos/taos_driver.c:25:
./70000/taos_driver.c:281:23: error: use of undeclared identifier 'ZEND_THIS'
    dbh = Z_PDO_DBH_P(ZEND_THIS);
                      ^
1 error generated.
make: *** [taos_driver.lo] Error 1

**Comment by bearlord** [comment]
先下载release1.0.0的版本吧。

> https://github.com/bearlord/pdo_taos/releases/tag/1.0.0。

你刚才的报错，是我新增了getServerInfo方法导致的，1.0.0的版本没这个方法，应该不会报错。PHP7.3以上和以下的API不一样，平时都拿7.4测试，没验证7.3以下版本了。稍后我做兼容吧。

**Comment by wolftail** [comment]
可以了，多谢👍
