### ISSUE TITLE
configure无法通过

### ISSUE THREAD

**Issue by bioinformatist** [bearlord/pdo_taos#3]
`phpize`运行正常无报错，之后`./configure`的时候发现依赖自身？无法通过：
![image](https://user-images.githubusercontent.com/17194719/158932638-fe424f5d-9389-499e-8278-123b19b36b2a.png)
测试了php 7.4.3和8.0.16均不行

如果是我自己姿势问题，望指点...

---

公司的后端技术栈主要是php workerman
也有用到一些8.1的新特性，所以希望早日支持8.1
我们会持续follow进展，感谢您为社区做的贡献
项目上线后会在显眼位置增加致谢说明！

**Comment by bearlord** [comment]
看来我的提示应该写的有问题，我需要改下提示。
pdo_taos需要依赖 libtaos，涛思数据的库文件。也就是说你需要安装涛思数据的服务端或者客户端。 

config.m4中

  # --with-pdo_taos -> check with-path
  SEARCH_PATH="/usr/local/taos /usr/local"
  SEARCH_FOR="/include/taos.h"
  if test -r $PHP_PDO_TAOS/$SEARCH_FOR; then # path given as parameter
    PDO_TAOS_DIR=$PHP_PDO_TAOS
  else # search default path list
    AC_MSG_CHECKING([for pdo_taos files in default path])
    for i in $SEARCH_PATH ; do
      if test -r $i/$SEARCH_FOR; then
        PDO_TAOS_DIR=$i
        AC_MSG_RESULT(found in $i)
      fi
    done
  fi

首先本目录中搜索 [include/taos.h]，找不到了，再去系统搜索[/usr/local/taos/include/taos.h, /usr/local/include/taos.h]。你的现在是两个都没有找到，报错了。但是我的提示写错了，汗~~。

等下我改提示。

**Comment by bearlord** [comment]
错误提示 已修改。请先从dev-master克隆代码试试。

**Comment by bioinformatist** [comment]
收到，我按照您的指引再试下。对php的编译流程不熟悉，感谢帮助~

**Comment by bioinformatist** [comment]
安装成功了，感谢。
![image](https://user-images.githubusercontent.com/17194719/159032427-213a9a92-6ead-4956-bbdd-b8022e3c1eff.png)
我的TDengine是丢在Docker container里运行的，方便项目上线时部署（虽然官方不鼓励这样做，但是我可以用自己的Dockerfile）
所以理论上我最好只需要安装client就好了~
参照您上面的描述和官方文档，虽然Lite版只有C/C++扩展，但是必要的头文件应该有了，我试了一下，果然可以。
您看是否有必要更新一下README，或者不嫌弃的话，我可以PR补充一下的
另由于我们最近在一个项目上尝试全面迁移至TDengine，且后端技术栈为纯php，应该对您的pdo项目依赖蛮重，请问是否方便添加微信方便沟通（issue仍会以社区规范化的形式提出，仅做业务交流）？
我的微信号是`MTMwNDQyNDAzMDQK`（base64-encoded，non-salted）
原谅唐突:smile:
