### ISSUE TITLE
编译报错 gcc9.4.0

### ISSUE THREAD

**Issue by xiejunyu** [bearlord/pdo_taos#4]
cc -I/www/server/php/74/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_SIGNALS -I. -I/www/xjy/pdo_taos -DPHP_ATOM_INC -I/www/xjy/pdo_taos/include -I/www/xjy/pdo_taos/main -I/www/xjy/pdo_taos -I/www/server/php/74/include/php -I/www/server/php/74/include/php/main -I/www/server/php/74/include/php/TSRM -I/www/server/php/74/include/php/Zend -I/www/server/php/74/include/php/ext -I/www/server/php/74/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /www/xjy/pdo_taos/taos_statement.c  -fPIC -DPIC -o .libs/taos_statement.o
In file included from /www/xjy/pdo_taos/taos_statement.c:23:
/www/xjy/pdo_taos/70300/taos_statement.c: In function ‘pdo_taos_stmt_get_col’:
/www/xjy/pdo_taos/70300/taos_statement.c:462:49: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
  462 |                     sprintf(time_value, "%s.%03ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000));
      |                                             ~~~~^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |             |
      |                                                 long int      int
      |                                             %03d
/www/xjy/pdo_taos/70300/taos_statement.c:464:49: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
  464 |                     sprintf(time_value, "%s.%06ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000));
      |                                             ~~~~^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |             |
      |                                                 long int      int
      |                                             %06d
/www/xjy/pdo_taos/70300/taos_statement.c:466:49: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type ‘int’ [-Wformat=]
  466 |                     sprintf(time_value, "%s.%09ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000000));
      |                                             ~~~~^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 |             |
      |                                                 long int      int
      |                                             %09d
/www/xjy/pdo_taos/70300/taos_statement.c:466:45: warning: ‘%09ld’ directive writing between 9 and 10 bytes into a region of size between 0 and 29 [-Wformat-overflow=]
  466 |                     sprintf(time_value, "%s.%09ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000000));
      |                                             ^~~~~
/www/xjy/pdo_taos/70300/taos_statement.c:466:41: note: directive argument in the range [-999999999, 999999999]
  466 |                     sprintf(time_value, "%s.%09ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000000));
      |                                         ^~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /www/server/php/74/include/php/Zend/zend_portability.h:49,
                 from /www/server/php/74/include/php/Zend/zend_types.h:25,
                 from /www/server/php/74/include/php/Zend/zend.h:27,
                 from /www/server/php/74/include/php/main/php.h:33,
                 from /www/xjy/pdo_taos/taos_statement.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 11 and 41 bytes into a destination of size 30
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /www/xjy/pdo_taos/taos_statement.c:23:
/www/xjy/pdo_taos/70300/taos_statement.c:464:45: warning: ‘%06ld’ directive writing between 6 and 7 bytes into a region of size between 0 and 29 [-Wformat-overflow=]
  464 |                     sprintf(time_value, "%s.%06ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000));
      |                                             ^~~~~
/www/xjy/pdo_taos/70300/taos_statement.c:464:41: note: directive argument in the range [-999999, 999999]
  464 |                     sprintf(time_value, "%s.%06ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000000));
      |                                         ^~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /www/server/php/74/include/php/Zend/zend_portability.h:49,
                 from /www/server/php/74/include/php/Zend/zend_types.h:25,
                 from /www/server/php/74/include/php/Zend/zend.h:27,
                 from /www/server/php/74/include/php/main/php.h:33,
                 from /www/xjy/pdo_taos/taos_statement.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 8 and 38 bytes into a destination of size 30
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /www/xjy/pdo_taos/taos_statement.c:23:
/www/xjy/pdo_taos/70300/taos_statement.c:462:45: warning: ‘%03ld’ directive writing between 3 and 4 bytes into a region of size between 0 and 29 [-Wformat-overflow=]
  462 |                     sprintf(time_value, "%s.%03ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000));
      |                                             ^~~~~
/www/xjy/pdo_taos/70300/taos_statement.c:462:41: note: directive argument in the range [-999, 999]
  462 |                     sprintf(time_value, "%s.%03ld", time_str, (int32_t)(*((int64_t *) row[colno]) % 1000));
      |                                         ^~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from /www/server/php/74/include/php/Zend/zend_portability.h:49,
                 from /www/server/php/74/include/php/Zend/zend_types.h:25,
                 from /www/server/php/74/include/php/Zend/zend.h:27,
                 from /www/server/php/74/include/php/main/php.h:33,
                 from /www/xjy/pdo_taos/taos_statement.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 5 and 35 bytes into a destination of size 30
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/bin/sh /www/xjy/pdo_taos/libtool --mode=link cc -DPHP_ATOM_INC -I/www/xjy/pdo_taos/include -I/www/xjy/pdo_taos/main -I/www/xjy/pdo_taos -I/www/server/php/74/include/php -I/www/server/php/74/include/php/main -I/www/server/php/74/include/php/TSRM -I/www/server/php/74/include/php/Zend -I/www/server/php/74/include/php/ext -I/www/server/php/74/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -o pdo_taos.la -export-dynamic -avoid-version -prefer-pic -module -rpath /www/xjy/pdo_taos/modules  pdo_taos.lo taos_driver.lo taos_statement.lo -Wl,-rpath,/usr/driver -L/usr/driver -ltaos
cc -shared  .libs/pdo_taos.o .libs/taos_driver.o .libs/taos_statement.o  -L/usr/driver -ltaos  -Wl,-rpath -Wl,/usr/driver -Wl,-soname -Wl,pdo_taos.so -o .libs/pdo_taos.so
creating pdo_taos.la
(cd .libs && rm -f pdo_taos.la && ln -s ../pdo_taos.la pdo_taos.la)
/bin/sh /www/xjy/pdo_taos/libtool --mode=install cp ./pdo_taos.la /www/xjy/pdo_taos/modules
cp ./.libs/pdo_taos.so /www/xjy/pdo_taos/modules/pdo_taos.so
cp ./.libs/pdo_taos.lai /www/xjy/pdo_taos/modules/pdo_taos.la
PATH="$PATH:/sbin" ldconfig -n /www/xjy/pdo_taos/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /www/xjy/pdo_taos/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /www/server/php/74/lib/php/extensions/no-debug-non-zts-20190902/

**Comment by bearlord** [comment]
报的警告，应该是编译通过了。你用的什么系统，我复现一下，稍后做好兼容。

**Comment by jason-2026-x** [comment]
gcc  9.4.0
Ubuntu 20.04.1
php 7.4.28
编译是通过了,
fetchAll查询出来的时间中间被截掉了,不知道是不是编译报的警告导致的,麻烦你啦
[ts] => 2022-07-0:06.000

**Comment by bearlord** [comment]
我这编译警告，但是不会查询出错。 你可以 php-fpm  和 cli 都测试下，看是否都报错了。
如果还有报错，请把测试的数据表结构发一下。

```

root@ubuntu20:/home/bear/documents# cat /etc/issue
Ubuntu 20.04.4 LTS \n \l
root@ubuntu20:/home/bear/documents# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-Av3uEd/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
root@ubuntu20:/home/bear/documents# php -v
PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
root@ubuntu20:/home/bear/documents# php --ri pdo_taos

pdo_taos

PDO Driver for TDengine => enabled
TDengine(libtaos) Version  => 2.6.0.6
root@ubuntu20:/home/bear/documents# cat pdo_taos_3.php 
<?php

$t1 = microtime(true);

$dbh = new PDO("taos:host=127.0.0.1", "root", "taosdata"); 
$stmt = $dbh->query("select * from demo.t1 LIMIT 3 OFFSET 0");

$all = $stmt->fetchAll(PDO::FETCH_ASSOC);

print_r($all);

$t2 = microtime(true);

echo "run time: ". ($t2 - $t1) . "\n";
        
?>
root@ubuntu20:/home/bear/documents# php pdo_taos_3.php 
Array
(
    [0] => Array
        (
            [ts] => 2022-07-01 15:25:17.933
            [v_int] => 1
        )

)
run time: 0.0094621181488037

```
